import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  // {
  //   path: "",
  //   title: "Personal",
  //   icon: "mdi mdi-dots-horizontal",
  //   class: "nav-small-cap",
  //   extralink: true,
  //   submenu: [],
  // },
  {
    path: "/dashboard",
    title: "Dashboard",
    icon: "dashboard",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "",
    title: "IMPORT",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "/component/import/schedule",
    title: "IMPORT SCHEDULE",
    icon: "fas fa-ship",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/import/exwarehouse",
    title: "EX-WAREHOUSE",
    icon: "fas fa-th",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/import/unload",
    title: "UNLOAD",
    icon: "fas fa-truck-loading",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/import/impfumigation",
    title: "IMPORT FUMIGATION",
    icon: "fas fa-bug",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "",
    title: "STOCK CONTROL",
    icon: "",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "/component/stkctrl/genstocktags",
    title: "STOCK TAGS",
    icon: "fas fa-qrcode",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/stkctrl/soh",
    title: "STOCK ON HAND",
    icon: "fas fa-boxes",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/stkctrl/cdr",
    title: "CDR",
    icon: "fas fa-undo",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/stkctrl/idr",
    title: "INTERNAL DAMAGE",
    icon: "fas fa-times-circle",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/stkctrl/pallet",
    title: "PALLET",
    icon: "fas fa-pallet",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/stkctrl/foc",
    title: "FOC.",
    icon: "fas fa-thumbs-up",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "",
    title: "SALES",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "/component/sales/saleorders",
    title: "SALES ORDERS",
    icon: "cart-arrow-down",
    class: "",
    extralink: false,
    submenu: [],
  },
  // LG
  {
    path: "",
    title: "LOGISTICS",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "/component/logistics/pendingdelivery",
    title: "DELIVERY",
    icon: "truck-moving",
    class: "",
    extralink: false,
    submenu: [],
  },
  // {
  //   path: "/component/card",
  //   title: "Card",
  //   icon: "mdi mdi-blur-radial",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/accordion",
  //   title: "Accordion",
  //   icon: "mdi mdi-equal",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/alert",
  //   title: "Alert",
  //   icon: "mdi mdi-message-bulleted",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/carousel",
  //   title: "Carousel",
  //   icon: "mdi mdi-view-carousel",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/dropdown",
  //   title: "Dropdown",
  //   icon: "mdi mdi-arrange-bring-to-front",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/modal",
  //   title: "Modal",
  //   icon: "mdi mdi-tablet",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/pagination",
  //   title: "Pagination",
  //   icon: "mdi mdi-backburger",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/poptool",
  //   title: "Popover & Tooltip",
  //   icon: "mdi mdi-image-filter-vintage",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/progressbar",
  //   title: "Progressbar",
  //   icon: "mdi mdi-poll",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/rating",
  //   title: "Ratings",
  //   icon: "mdi mdi-bandcamp",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/tabs",
  //   title: "Tabs",
  //   icon: "mdi mdi-sort-variant",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/timepicker",
  //   title: "Timepicker",
  //   icon: "mdi mdi-calendar-clock",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/buttons",
  //   title: "Button",
  //   icon: "mdi mdi-toggle-switch",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/toast",
  //   title: "Toast",
  //   icon: "mdi mdi-alert",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
];
